language: generic
install:
    - git clone https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
before_script:
    - uname -a
    - vim --version
script:
    - ./vim-themis/bin/themis test/
